modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="stuffplus" #mandatory
version="1.0" #mandatory
displayName="Stuff Plus" #mandatory
credits="Person who did most of the work: TheDarkGamer1YT. Check out his youtube. Kvm718 also helped" #optional
authors="TheDarkGamer1YT, kvm718" #optional
description='''
lol hi

this is

a description
'''
[[dependencies.stuffplus]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.stuffplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
